config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root 'static_pages#home'
  get '/new_game', to: 'games#new'
  get '/help', to: 'static_pages#help'
  get '/signup', to: 'users#new'
  resources :games
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  get '/log_in_one', to: 'sessions#new_one'
  post 'log_in_one', to: 'sessions#create_one'
  delete '/log_out_one', to: 'sessions#destroy_one'

  get '/log_in_two', to: 'sessions#new_two'
  post 'log_in_two', to: 'sessions#create_two'
  delete '/log_out_two', to: 'sessions#destroy_two'

  post 'games/update_player'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @games = Game.last(10).reverse
  end

  def help
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
    This is the help page.
</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<div class="container">
  <div class="center jumbotron">
    <h1>Welcome to Darts</h1>
  </div>
  <div class="row">
    <div class="col-sm-2">
      <%= button_to('Cricket', new_game_path, method: :get) %>
      <%= button_to('Around the World', '#') %>
      <%= button_to('301', '#') %>
    </div>
    <div class="col-sm-10">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Player One</th>
            <th>Score</th>
            <th>Player Two</th>
          </tr>
        </thead>
          <tbody>
            <% @games.each do |game| %>
              <tr>
                <td><%= link_to User.find(game[:player_one]).name, User.find(game[:player_one]) %></td>
                <td><%= link_to "#{game[:player_one_score] || 0} - #{game[:player_two_score] || 0}", game, method: :get %></td>
                <td><%= link_to User.find(game[:player_two]).name, User.find(game[:player_two]) %></td>
              </tr>
            <% end %>
          </tbody>
      </table>
    </div>
  </div>
</div>

<!-- will show recent games -->