config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root 'static_pages#home'
  get '/new_game', to: 'games#new'
  get '/help', to: 'static_pages#help'
  get '/signup', to: 'users#new'
  resources :games
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  get '/log_in_one', to: 'sessions#new_one'
  post 'log_in_one', to: 'sessions#create_one'
  delete '/log_out_one', to: 'sessions#destroy_one'

  get '/log_in_two', to: 'sessions#new_two'
  post 'log_in_two', to: 'sessions#create_two'
  delete '/log_out_two', to: 'sessions#destroy_two'

  post 'games/update_player'

end

app/models/game.rb
class Game < ApplicationRecord
  attr_accessor :player_one_15, :player_two_15, :player_one_16, :player_two_16, :player_one_17, :player_two_17, :player_one_18, :player_two_18, :player_one_19, :player_two_19, :player_one_20, :player_two_20, :player_one_be, :player_two_be, :player_one_score, :player_two_score
  validates :player_one, :player_two, presence: true
  validate :check_player_one_and_player_two

  def check_player_one_and_player_two
    errors.add(:player_one, 'You cannot play against yourself') if player_one == player_two
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  PLAYERS = ['one', 'two']

  def new
    @game = Game.new
    if authenticated_one? && authenticated_two?
      @game['player_one'] = @current_user_one.id
      @game['player_two'] = @current_user_two.id
      if @game.save
        redirect_to @game
      else
        flash[:danger] = 'There was an error, please try again.'
        redirect_to root_path
      end
    else
      flash[:danger] = 'Two players to be signed in to start a game.'
      redirect_to root_path
    end
  end

  def index
    @games = Game.paginate(page: params[:page])
  end

  def show
    @game = Game.find(params[:id])
    @player_one_name = User.find(@game.player_one).name
    @player_two_name = User.find(@game.player_two).name
  end

  def update_player
    @game = Game.find(params[:id])
    if (current_user_one && current_user_one.id == @game.player_one) && (current_user_two && current_user_two.id == @game.player_two)
      other_player = params[:player] == 'one' ? PLAYERS[1] : PLAYERS[0]
      main_score = @game['player_' + params[:player] + '_' + params[:score]]
      other_score = @game['player_' + other_player + '_' + params[:score]]
      if main_score > 2 && other_score < 3
        initial_score = @game[('player_' + params[:player] + '_score')]
        @game[('player_' + params[:player] + '_score')] = initial_score + params[:score].to_i
        @game[('player_' + params[:player] + '_score')] = initial_score + 25 if params[:score] == 'be'
      end
      if main_score < 3 || other_score < 3
        initial_score = @game[('player_' + params[:player] + '_' + params[:score])]
        @game[('player_' + params[:player] + '_' + params[:score])] = initial_score + 1
      end
      @game.save
    end
  end

    def game_params
      params.require(:game)
    end
end

app/helpers/games_helper.rb
module GamesHelper
  def is_editable?
    return (!current_user_one.nil? && current_user_one.id == @game.player_one) && (!current_user_two.nil? && current_user_two.id == @game.player_two) && !game_over? ? 1 : 0
  end

  def game_over?
    if all_closed?('one') && @game[:player_one_score] > @game[:player_two_score]
      true
    elsif all_closed?('two') && @game[:player_two_score] > @game[:player_one_score]
      true
    else
      false
    end
  end

  private

    def all_closed?(player_num)
      player = "player_#{player_num}_"
      returner = true
      returner = @game[player + '15'] >= 3 && returner
      returner = @game[player + '16'] >= 3 && returner
      returner = @game[player + '17'] >= 3 && returner
      returner = @game[player + '18'] >= 3 && returner
      returner = @game[player + '19'] >= 3 && returner
      returner = @game[player + '20'] >= 3 && returner
      returner = @game[player + 'be'] >= 3 && returner
    end
end

app/views/games/_scorer.html.erb
<!-- scorer partial -->
<div class="row">
  <div class="col-sm-4">
    <h1><%= button_to("#{@game['player_one_' + score]}", games_update_player_path(id: @game.id, player: 'one', score: score), method: :post, class: 'button', id: "player_one_#{score}") %></h1>
  </div>
  <div class="col-sm-1">
    <%= image_tag('zero.png', class: 'image', id: "player_one_#{score}_img") if @game['player_one_' + score] == 0 %>
    <%= image_tag('one.png', class: 'image', id: "player_one_#{score}_img") if @game['player_one_' + score] == 1 %>
    <%= image_tag('two.png', class: 'image', id: "player_one_#{score}_img") if @game['player_one_' + score] == 2 %>
    <%= image_tag('three.png', class: 'image', id: "player_one_#{score}_img") if @game['player_one_' + score] > 2 %>
  </div>
  <div class="col-sm-2">
      <h1><%= score %></h1>
  </div>
  <div class="col-sm-1">
    <%= image_tag('zero.png', class: 'image', id: "player_two_#{score}_img") if @game['player_two_' + score] == 0 %>
    <%= image_tag('one.png', class: 'image', id: "player_two_#{score}_img") if @game['player_two_' + score] == 1 %>
    <%= image_tag('two.png', class: 'image', id: "player_two_#{score}_img") if @game['player_two_' + score] == 2 %>
    <%= image_tag('three.png', class: 'image', id: "player_two_#{score}_img") if @game['player_two_' + score] > 2 %>
  </div>
  <div class="col-sm-4">
    <h1><%= button_to("#{@game['player_two_' + score]}", games_update_player_path(id: @game.id, player: 'two', score: score), method: :post, class: 'button', id: "player_two_#{score}") %></h1>
  </div>
</div>

app/views/games/index.html.erb
<% provide(:title, 'All games') %>
<%= will_paginate %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Player One</th>
        <th>Score</th>
        <th>Player Two</th>
      </tr>
    </thead>
      <tbody>
        <% @games.each do |game| %>
          <tr>
            <td><%= User.find(game[:player_one]).name %></td>
            <td><%= link_to "#{game[:player_one_score] || 0} - #{game[:player_two_score] || 0}", game, method: :get %></td>
            <td><%= User.find(game[:player_two]).name %></td>
          </tr>
        <% end %>
      </tbody>
  </table>
<%= will_paginate %>

app/views/games/show.html.erb
<% provide(:title, "#{@player_one_name} vs. #{@player_two_name}") %>
<div id='editable-var', class='hidden'><%= is_editable? %></div>
<div class="container">
    <!-- names -->
    <div class="row">
      <div class="col-sm-4">
        <%= content_tag :h1, id: 'player_one_score' do %>
          <%= "#{@game[:player_one_score]}" %>
        <% end %>
      </div>
      <div class="col-sm-4">
        <h1>Score</h1>
      </div>
      <div class="col-sm-4">
        <h1 id='player_two_score'><%= "#{@game[:player_two_score]}" %></h1>
      </div>
  </div>
  <% ['20', '19', '18', '17', '16', '15', 'be'].each do |num| %>
    <%= render partial: 'scorer', locals: { score: num } %>
  <% end %>
</div>