config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root 'static_pages#home'
  get '/new_game', to: 'games#new'
  get '/help', to: 'static_pages#help'
  get '/signup', to: 'users#new'
  resources :games
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  get '/log_in_one', to: 'sessions#new_one'
  post 'log_in_one', to: 'sessions#create_one'
  delete '/log_out_one', to: 'sessions#destroy_one'

  get '/log_in_two', to: 'sessions#new_two'
  post 'log_in_two', to: 'sessions#create_two'
  delete '/log_out_two', to: 'sessions#destroy_two'

  post 'games/update_player'

end

app/views/layouts/_footer.html.erb
<footerclass="navbar navbar-fixed-bottom navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-center">
        <li><%= link_to 'Search for players', users_path %></li>
      </ul>
    </nav>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <a class="navbar-brand" href="/">Darts</a>
      <ul class="nav navbar-nav navbar-left">
        <% if logged_in_one? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= @current_user_one.name %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Account", @current_user_one %></li>
              <li class="divider"></li>
              <li>
                <li><%= link_to 'Log Out', log_out_one_path, method: 'delete' %></li>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'P1 Log In', log_in_one_path %></li>
        <% end %>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if logged_in_two? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= @current_user_two.name %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Account", @current_user_two %></li>
              <li class="divider"></li>
              <li>
                <%= link_to 'P2 Log Out', log_out_two_path, method: 'delete' %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'P2 Log In', log_in_two_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>